EXEC spAltaEjemplar(1, 1,'disponible');
EXEC spAltaEjemplar(1, 2,'no sale');
EXEC spAltaEjemplar(2, 1, 'disponible');
EXEC spAltaEjemplar(3, 1, 'disponible');
EXEC spAltaEjemplar(3, 2, 'disponible');
EXEC spAltaEjemplar(4, 1, 'disponible');
EXEC spAltaEjemplar(4, 2, 'disponible');
EXEC spAltaEjemplar(4, 3, 'no sale');
EXEC spAltaEjemplar(5, 1, 'disponible');
EXEC spAltaEjemplar(5, 2, 'mantenimiento');
EXEC spAltaEjemplar(6, 1, 'disponible');
EXEC spAltaEjemplar(7, 1, 'disponible');
EXEC spAltaEjemplar(8, 1, 'disponible');
EXEC spAltaEjemplar(8, 2, 'disponible');
EXEC spAltaEjemplar(9, 1, 'disponible');
EXEC spAltaEjemplar(9, 2, 'disponible');
EXEC spAltaEjemplar(10, 1, 'disponible');
EXEC spAltaEjemplar(11, 1, 'disponible');
EXEC spAltaEjemplar(12, 1, 'disponible');
EXEC spAltaEjemplar(12, 2, 'no sale');
EXEC spAltaEjemplar(13, 1, 'disponible');
EXEC spAltaEjemplar(13, 2, 'disponible');
COMMIT;