EXEC spAltaMaterial('libro', 'Don Quijote de la Mancha I', 'Caballeresco', 'Coleccion General', 'HG4025');
EXEC spAltaMaterial('libro', 'Don Quijote de la Mancha II', 'Caballeresco', 'Coleccion General', 'HG4025');
EXEC spAltaMaterial('libro', 'Historias de Nueva Orleans', 'Novela', 'Coleccion General', 'PS34235');
EXEC spAltaMaterial('libro', 'El Principito', 'Aventura', 'Coleccion General', 'PS5434');
EXEC spAltaMaterial('libro', 'El Principe', 'Politica', 'Coleccion Especial', 'QR3445');
EXEC spAltaMaterial('libro', 'Diplomacia', 'Politica', 'Coleccion Especial', 'QA1234');
EXEC spAltaMaterial('libro', 'Los Windsor', 'Biografias', 'Coleccion Especial', 'MS357');
EXEC spAltaMaterial('libro', 'El Ultimo Emperador', 'Autobiografia', 'Fondo Antiguo', 'JK3875');
EXEC spAltaMaterial('libro', 'Fortunata y Jacinta', 'Novela', 'Fondo Antiguo', 'RS3258');
EXEC spAltaMaterial('tesis', 'Academia para la Policia Federal', 'Politica', 'Tesis', 'TS2353');
EXEC spAltaMaterial('tesis', 'Actutud de los estudiantes', 'Educacion', 'Tesis', 'TS3235');
EXEC spAltaMaterial('tesis', 'Espacio-Tiempo', 'Fisica', 'Tesis', 'TS9438');
EXEC spAltaMaterial('tesis', 'Accesorias mercantiles', 'Economia', 'Tesis', 'TS3258');
COMMIT;