EXEC spAltaEjemplar(1,'disponible');
EXEC spAltaEjemplar(1,'no sale');
EXEC spAltaEjemplar(2, 'disponible');
EXEC spAltaEjemplar(3, 'disponible');
EXEC spAltaEjemplar(3, 'disponible');
EXEC spAltaEjemplar(4, 'disponible');
EXEC spAltaEjemplar(4, 'disponible');
EXEC spAltaEjemplar(4, 'no sale');
EXEC spAltaEjemplar(5, 'disponible');
EXEC spAltaEjemplar(5, 'mantenimiento');
EXEC spAltaEjemplar(6, 'disponible');
EXEC spAltaEjemplar(7, 'disponible');
EXEC spAltaEjemplar(8, 'disponible');
EXEC spAltaEjemplar(8, 'disponible');
EXEC spAltaEjemplar(9, 'disponible');
EXEC spAltaEjemplar(9, 'disponible');
EXEC spAltaEjemplar(10, 'disponible');
EXEC spAltaEjemplar(11, 'disponible');
EXEC spAltaEjemplar(12, 'disponible');
EXEC spAltaEjemplar(12, 'no sale');
EXEC spAltaEjemplar(13, 'disponible');
EXEC spAltaEjemplar(13, 'disponible');
COMMIT;